### ISSUE TITLE
一份vue项目的eslintrc文档说明

### ISSUE THREAD

**Issue by calali** [calali/blog#25]
```YAML
{
  //一个环境定义了一组预定义的全局变量。
  //https://github.com/sindresorhus/globals/blob/master/globals.json
  "env": {
    "browser": true,//浏览器环境中的全局变量。
    "commonjs": true,//CommonJS 全局变量和 CommonJS 作用域 (用于 Browserify/WebPack 打包的只在浏览器中运行的代码)。
    "es6": true,// 启用除了 modules 以外的所有 ECMAScript 6 特性
    "node": true,//Node.js 全局变量和 Node.js 作用域。这一行去掉没有任何影响
    "mocha": true //添加所有的 Mocha 测试全局变量。
  },
  "parserOptions": {
    //使得eslint可以静态分析代码的解析器，默认的是espree，只支持最新的eacascript，这里使用babel从而可以支持验证所有有实验性的新特性和非标准的语法如typescript
    //不能写在一级parser属性里是因为eslint-plugin-vue plugin的官文文档说明一级parse选项要求使用"vue-eslint-parser"
    "parser": "babel-eslint"
  },
  //一个配置文件可以被基础配置中的已启用的规则继承。
  //插件名称可以省略 eslint-plugin- 前缀。下面是eslint-plugin-vue的省略写法。选取的配置是essential
  //eslint-config-airbnb的默认输出规则是airbnb，包含ecmascript 6+和react
  "extends": ["plugin:vue/essential", "airbnb"],
  //脚本在执行期间访问的额外的全局变量。
  "globals": {
    // 定义expect全局变量。布尔值 false 和字符串值 "readable" 等价于 "readonly"
    "expect": false
  },
  //ESLint 支持在配置文件添加共享设置。看起来是对下面列出的格式的文件支持import检验
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [".js", ".jsx", ".ts", ".tsx", ".vue", ".json"]
      }
    }
  },
  "rules": {
    "arrow-parens": [2, "as-needed", { "requireForBlockBody": false }],
    "comma-dangle": [2, "always-multiline"],
    "import/extensions": 0,
    "import/no-extraneous-dependencies": [2, { "devDependencies": ["**/*Test.js"] }],
    "import/prefer-default-export": 0,
    "no-param-reassign": [2, { "props": false }],
    "no-plusplus": [2, { "allowForLoopAfterthoughts": true }],
    "prefer-const": [2, { "destructuring": "all", "ignoreReadBeforeAssign": false }],
    "prefer-destructuring": 0,
    "prefer-promise-reject-errors": 0,
    "semi": [2, "never"],
    "sort-imports": 0,
    "vue/script-indent": [2, 2, { "baseIndent": 1, "switchCase": 1 }]
  },
  //若要禁用一组文件的配置文件中的规则，请使用 overrides 和 files。对vue文件禁用缩进检查
  "overrides": [
    {
      "files": ["*.vue"],
      "rules": {
        "indent": 0
      }
    }
  ]
}

```
